web:
  hpa:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

worker:
  hpa:
    enabled: true

environmentVariables:
  ENABLE_SOCIAL_AUTH: true
  GLITCHTIP_DOMAIN: https://staging.glitchtip.com
