image: node:12-alpine

variables:
  CHROME_BIN: chromium-browser
  npm_config_cache: $CI_PROJECT_DIR/.npm
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: registry.gitlab.com/dasch8/angular-ci:latest
  script:
    - npm ci
    - npm run lint
    - npm run test -- --progress false --watch=false --browsers=Chromium_CI

build-assets:
  stage: test
  cache:
    paths:
      - .npm/
  script:
    - npm ci
    - node --max_old_space_size=6000 node_modules/@angular/cli/bin/ng build --prod --progress false
  artifacts:
    paths:
      - dist/

build-docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  dependencies:
    - build-assets
  only:
    - master
    - staging
    - dev
  script:
    - echo "Start build docker step $CI_REGISTRY_IMAGE commit ref $CI_COMMIT_REF_NAME"
    - trap '' PIPE
    - VERSION=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' package.json | head -n 1)
    - echo "Build version $VERSION ci registry image $CI_REGISTRY_IMAGE commit ref $CI_COMMIT_REF_NAME"
    - docker build -f Dockerfile.prod -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} -t ${CONTAINER_IMAGE} --build-arg GLITCHTIP_VERSION=$VERSION .
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then docker tag ${CONTAINER_IMAGE} ${CI_REGISTRY_IMAGE}:latest; fi
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - docker push ${CONTAINER_IMAGE}
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then docker push ${CI_REGISTRY_IMAGE}:latest; fi

pages:
  stage: deploy
  script:
    - npm ci
    - npm run ng build marketing -- --prod
    - npm run ng run marketing:server
    - npx angular-prerender --browser-target=marketing:build --server-target=marketing:server
    - mv dist/marketing public
  artifacts:
    paths:
      - public
  only:
    - master
    - staging
    - dev

deploy-staging:
  stage: deploy
  image: lwolf/helm-kubectl-docker
  script:
    - helm upgrade glitchtip-staging ./chart --set image.tag=${CI_COMMIT_SHORT_SHA} --reuse-values
  environment:
    name: staging
    url: https://staging.glitchtip.com
  only:
    - master
