apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glitchtip.fullname" . }}
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
data:
  ENABLE_SOCIAL_AUTH: {{ .Values.enableSocialAuth | quote }}