apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitchtip.fullname" . }}
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "databaseURL is a required value." .Values.databaseURL | b64enc | quote }}
  SECRET_KEY: {{ required "secretKey is a required value." .Values.secretKey | b64enc | quote }}
  REDIS_URL: {{ printf "redis://:@glitchtip-staging-redis-master:6379/0" | b64enc | quote }}
{{- if .Values.stripeLiveSecretKey }}
  STRIPE_LIVE_SECRET_KEY: {{ .Values.stripeLiveSecretKey | b64enc | quote }}
{{- end }}
{{- if .Values.djstripeWebhookSecret }}
  DJSTRIPE_WEBHOOK_SECRET: {{ .Values.djstripeWebhookSecret | b64enc | quote }}
{{- end }}
