apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glitchtip.fullname" . }}
  labels:
    {{- include "glitchtip.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "databaseURL is a required value." .Values.databaseURL | b64enc | quote }}
  SECRET_KEY: {{ required "secretKey is a required value." .Values.secretKey | b64enc | quote }}
  REDIS_URL: {{ printf "redis://:@glitchtip-staging-glitchtip-redis-master:6379/0" | b64enc | quote }}